/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as PedidosRouteImport } from './routes/pedidos'
import { Route as MonteSeuPcRouteImport } from './routes/monte-seu-pc'
import { Route as MinhasBuildsRouteImport } from './routes/minhas-builds'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutoIdRouteImport } from './routes/produto.$id'

const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosRoute = PedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const MonteSeuPcRoute = MonteSeuPcRouteImport.update({
  id: '/monte-seu-pc',
  path: '/monte-seu-pc',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhasBuildsRoute = MinhasBuildsRouteImport.update({
  id: '/minhas-builds',
  path: '/minhas-builds',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoIdRoute = ProdutoIdRouteImport.update({
  id: '/produto/$id',
  path: '/produto/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/minhas-builds': typeof MinhasBuildsRoute
  '/monte-seu-pc': typeof MonteSeuPcRoute
  '/pedidos': typeof PedidosRoute
  '/produtos': typeof ProdutosRoute
  '/produto/$id': typeof ProdutoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/minhas-builds': typeof MinhasBuildsRoute
  '/monte-seu-pc': typeof MonteSeuPcRoute
  '/pedidos': typeof PedidosRoute
  '/produtos': typeof ProdutosRoute
  '/produto/$id': typeof ProdutoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/minhas-builds': typeof MinhasBuildsRoute
  '/monte-seu-pc': typeof MonteSeuPcRoute
  '/pedidos': typeof PedidosRoute
  '/produtos': typeof ProdutosRoute
  '/produto/$id': typeof ProdutoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/checkout'
    | '/login'
    | '/minhas-builds'
    | '/monte-seu-pc'
    | '/pedidos'
    | '/produtos'
    | '/produto/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/checkout'
    | '/login'
    | '/minhas-builds'
    | '/monte-seu-pc'
    | '/pedidos'
    | '/produtos'
    | '/produto/$id'
  id:
    | '__root__'
    | '/'
    | '/cadastro'
    | '/checkout'
    | '/login'
    | '/minhas-builds'
    | '/monte-seu-pc'
    | '/pedidos'
    | '/produtos'
    | '/produto/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroRoute: typeof CadastroRoute
  CheckoutRoute: typeof CheckoutRoute
  LoginRoute: typeof LoginRoute
  MinhasBuildsRoute: typeof MinhasBuildsRoute
  MonteSeuPcRoute: typeof MonteSeuPcRoute
  PedidosRoute: typeof PedidosRoute
  ProdutosRoute: typeof ProdutosRoute
  ProdutoIdRoute: typeof ProdutoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos': {
      id: '/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof PedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monte-seu-pc': {
      id: '/monte-seu-pc'
      path: '/monte-seu-pc'
      fullPath: '/monte-seu-pc'
      preLoaderRoute: typeof MonteSeuPcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minhas-builds': {
      id: '/minhas-builds'
      path: '/minhas-builds'
      fullPath: '/minhas-builds'
      preLoaderRoute: typeof MinhasBuildsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$id': {
      id: '/produto/$id'
      path: '/produto/$id'
      fullPath: '/produto/$id'
      preLoaderRoute: typeof ProdutoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroRoute: CadastroRoute,
  CheckoutRoute: CheckoutRoute,
  LoginRoute: LoginRoute,
  MinhasBuildsRoute: MinhasBuildsRoute,
  MonteSeuPcRoute: MonteSeuPcRoute,
  PedidosRoute: PedidosRoute,
  ProdutosRoute: ProdutosRoute,
  ProdutoIdRoute: ProdutoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
